"""LiteLLM proxy callback that writes Tokdash usage JSONL.

Why this exists
---------------
LiteLLM's default proxy access log records successful HTTP requests, e.g.
``INFO ... "POST /v1/messages" 200 OK``, but token usage is normally only
available in the response/stream object. Tokdash's ``LitellmProxyParser`` reads
the sidecar JSONL generated by this callback instead of scraping fragile text
logs.

Example config.yaml:

    litellm_settings:
      callbacks:
        - scripts.tokdash_litellm_callback.tokdash_callback

Set the output path with one of:

    TOKDASH_LITELLM_PROXY_JSONL
    LITELLM_TOKDASH_JSONL
    LITELLM_PROXY_USAGE_JSONL

Default: ~/.tokdash/litellm-proxy-usage.jsonl
"""
from __future__ import annotations

import json
import os
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

try:  # LiteLLM imports this module inside the proxy process.
 from litellm.integrations.custom_logger import CustomLogger
except Exception:  # pragma: no cover - lets tests/imports work without LiteLLM.
 class CustomLogger:  # type: ignore
  pass


def _output_path() -> Path:
 explicit = (
  os.environ.get("TOKDASH_LITELLM_PROXY_JSONL", "").strip()
  or os.environ.get("LITELLM_TOKDASH_JSONL", "").strip()
  or os.environ.get("LITELLM_PROXY_USAGE_JSONL", "").strip()
 )
 if explicit:
  return Path(explicit).expanduser()
 return Path(os.environ.get("TOKDASH_DATA_DIR", "~/.tokdash")).expanduser() / "litellm-proxy-usage.jsonl"


def _as_dict(value: Any) -> Dict[str, Any]:
 if isinstance(value, dict):
  return value
 if value is None:
  return {}
 try:
  dumped = value.model_dump()
  return dumped if isinstance(dumped, dict) else {}
 except Exception:
  pass
 try:
  return dict(value)
 except Exception:
  pass
 attrs = getattr(value, "__dict__", None)
 return attrs if isinstance(attrs, dict) else {}


def _usage_dict(response_obj: Any) -> Dict[str, Any]:
 response = _as_dict(response_obj)
 usage = response.get("usage")
 if usage is None:
  usage = getattr(response_obj, "usage", None)
 usage_dict = _as_dict(usage)
 # Keep OpenAI-style names. The Tokdash parser knows prompt_tokens can be
 # cache-inclusive when prompt_tokens_details.cached_tokens exists.
 return usage_dict


def _metadata_dict(kwargs: Dict[str, Any]) -> Dict[str, Any]:
 metadata = _as_dict(kwargs.get("metadata"))
 litellm_params = _as_dict(kwargs.get("litellm_params"))
 params_metadata = _as_dict(litellm_params.get("metadata"))
 out: Dict[str, Any] = {}
 out.update(params_metadata)
 out.update(metadata)
 return out


def _request_id(kwargs: Dict[str, Any], response_obj: Any) -> str:
 metadata = _metadata_dict(kwargs)
 response = _as_dict(response_obj)
 for value in (
  metadata.get("request_id"),
  metadata.get("trace_id"),
  kwargs.get("litellm_call_id"),
  kwargs.get("request_id"),
  response.get("id"),
 ):
  if value:
   return str(value)
 return f"{int(time.time() * 1000)}-{os.getpid()}"


def _model(kwargs: Dict[str, Any], response_obj: Any) -> str:
 response = _as_dict(response_obj)
 metadata = _metadata_dict(kwargs)
 for value in (kwargs.get("model"), response.get("model"), metadata.get("model")):
  if value:
   return str(value)
 return "unknown"


def _provider(kwargs: Dict[str, Any]) -> str:
 litellm_params = _as_dict(kwargs.get("litellm_params"))
 metadata = _metadata_dict(kwargs)
 for value in (
  kwargs.get("custom_llm_provider"),
  litellm_params.get("custom_llm_provider"),
  metadata.get("provider"),
 ):
  if value:
   return str(value)
 return ""


def _dt_ms(value: Any) -> int:
 if isinstance(value, datetime):
  return int(value.astimezone(timezone.utc).timestamp() * 1000)
 if value is not None:
  try:
   f = float(value)
   if f >= 1e11:
    return int(f)
   if f > 0:
    return int(f * 1000)
  except Exception:
   pass
 return int(time.time() * 1000)


def _write_jsonl(record: Dict[str, Any]) -> None:
 path = _output_path()
 path.parent.mkdir(parents=True, exist_ok=True)
 with path.open("a", encoding="utf-8") as f:
  f.write(json.dumps(record, separators=(",", ":"), ensure_ascii=False) + "\n")


class TokdashUsageLogger(CustomLogger):
 def _record(self, kwargs: Dict[str, Any], response_obj: Any, start_time: Any, end_time: Any) -> Dict[str, Any]:
  usage = _usage_dict(response_obj)
  metadata = _metadata_dict(kwargs)
  record = {
   "timestamp": _dt_ms(end_time),
   "request_id": _request_id(kwargs, response_obj),
   "model": _model(kwargs, response_obj),
   "provider": _provider(kwargs),
   "usage": usage,
  }
  if metadata:
   # Keep only small scalar metadata useful for dedup/debugging.
   record["metadata"] = {
    str(k): v
    for k, v in metadata.items()
    if isinstance(v, (str, int, float, bool)) or v is None
   }
  return record

 def log_success_event(self, kwargs: Dict[str, Any], response_obj: Any, start_time: Any, end_time: Any) -> None:
  try:
   record = self._record(kwargs, response_obj, start_time, end_time)
   if record.get("usage"):
    _write_jsonl(record)
  except Exception:
   # Never break the proxy because metrics logging failed.
   return

 async def async_log_success_event(self, kwargs: Dict[str, Any], response_obj: Any, start_time: Any, end_time: Any) -> None:
  self.log_success_event(kwargs, response_obj, start_time, end_time)


tokdash_callback = TokdashUsageLogger()
